### ISSUE TITLE
Choice of Robomongo

### ISSUE THREAD

**Issue by smartel99** [mikeckennedy/mongodb-for-python-developers#6]
I was wondering: Why use robomongo instead of the provided MongoDB Compass? It works pretty well and has a fairly nice and easy to use GUI, so is it because of performance or something like that? Or is it simply because it wasn't released yet at the time you created the course, being the "thing they're working on" you mentioned in Robomongo: a better shell?

**Comment by mikeckennedy** [comment]
Hi, thanks for the question.

I like compass in some ways. I love robomongo in most ways. If they could have an offspring, that would rock!

But here's the thing. Compass is a total pain for doing ad-hoc quereis and other operations on the shell. You have to navigate a bunch of different text boxes, etc. And sometimes the option isn't there at all.

With robomongo, you get a sweet GUI. But the place you type, that is as full featured as the commandline shell in MongoDB. That's why I like more.

Best,
Michael
